# Generated by Django 5.0.6 on 2026-08-19 17:51

import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=documents.models.upload_to)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('llm_title', models.CharField(blank=True, default='', max_length=500)),
                ('llm_summary', models.TextField(blank=True, default='')),
                ('llm_keywords', models.JSONField(blank=True, default=list)),
                ('llm_language', models.CharField(blank=True, default='', max_length=50)),
                ('llm_raw_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
